#!/bin/sh

case "$1" in
  start)
    echo "Loading i2c drivers"
    modprobe i2c-dev 
    modprobe i2c-bcm2835
    ;;
  stop)
    echo "Unloading i2c drivers"
    modprobe -r i2c-dev 
    modprobe -r i2c-bcm2835
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0